# Generated by Django 2.2.12 on 2020-04-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docversion',
            name='preamble',
            field=models.TextField(blank=True, help_text='Преамбула документа', verbose_name='Преамбула'),
        ),
    ]
