# Generated by Django 2.2.12 on 2020-04-24 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_docversion_preamble'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='change',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.Document'),
        ),
    ]
