# Generated by Django 2.2.12 on 2020-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_document_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_status', models.CharField(help_text='Сведения о текущем статусе документа', max_length=30, verbose_name='Статус документа')),
            ],
            options={
                'verbose_name': 'Статус документа',
                'verbose_name_plural': 'Сведения о текущем статусе документа',
            },
        ),
    ]
