# Generated by Django 2.2.12 on 2020-05-02 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_docstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_status',
            field=models.ForeignKey(default=1, help_text='Сведения о текущем статусе документа', on_delete=django.db.models.deletion.PROTECT, to='catalog.DocStatus', verbose_name='Статус документа'),
            preserve_default=False,
        ),
    ]
